# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-19 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=0, max_length=255, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('number_of_files', models.IntegerField(default=0)),
                ('mode', models.CharField(default='Scramble', max_length=255)),
                ('down_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExpiredURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=0, max_length=255, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('number_of_files', models.IntegerField(default=0)),
                ('mode', models.CharField(default='Scramble', max_length=255)),
            ],
        ),
    ]
