# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scramble', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeurl',
            old_name='uuid',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='expiredurl',
            old_name='uuid',
            new_name='url',
        ),
    ]
