# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scramble', '0002_auto_20180201_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeurl',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
