# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-11 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scramble', '0003_activeurl_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyChain',
            fields=[
                ('active', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scramble.ActiveURL')),
                ('key_one', models.CharField(default=0, max_length=255)),
                ('key_two', models.CharField(default=0, max_length=255)),
                ('key_three', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ZipLock',
            fields=[
                ('active', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scramble.ActiveURL')),
                ('zipcode', models.CharField(default=0, max_length=255)),
            ],
        ),
    ]
