# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-14 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scramble', '0004_keychain_ziplock'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeurl',
            name='sessionToken',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
